version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels: ['npm', 'dependencies']
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels: ['cargo', 'dependencies']
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels: ['gitsubmodule', 'dependencies']
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels: ['github-actions', 'dependencies']
    commit-message:
      prefix: 'chore'
      include: 'scope'
