[package]
name = "sample-contract"
version = "0.1.0"
edition = "2021"

[lib]
name = "contract"
path = "contract.rs"
crate-type = ["cdylib"]

[dependencies]
three_em = { path = "../", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
