/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly "": {
    readonly "": unique symbol;
    [K: symbol]: T;
  };
}
export interface ExecuteContractResult {
  state: any;
  validity: Record<string, any>;
}
export function executeContract(
  tx: string,
  maybeHeight?: number | undefined | null,
): Promise<ExecuteContractResult>;
