/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ExecuteContractResult {
  state: any
  validity: Record<string, any>
}
export interface ExecuteConfig {
  host: string
  port: number
  protocol: string
}
export function simulateContract(contractId: string, contractInitState?: string | undefined | null, interactions: any, maybeConfig?: ExecuteConfig | undefined | null): Promise<ExecuteContractResult>
export function executeContract(tx: string, maybeHeight?: number | undefined | null, maybeConfig?: ExecuteConfig | undefined | null): Promise<ExecuteContractResult>
