name: build

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Awarnings

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false

          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            cross: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true

      - name: Use Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --color always --release --target ${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Get Build Name
        id: zip
        run: echo "::set-output name=name::three_em-${{ matrix.target }}-${{ github.ref == 'refs/heads/main' && 'canary' || 'dev' }}-$(git rev-parse --short HEAD)"

      - name: Upload ${{ github.ref == 'refs/heads/main' && 'Canary' || 'Dev' }} Builds
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.zip.outputs.name }}
          path: |
            target/${{ matrix.target }}/release/three_em
            target/${{ matrix.target }}/release/three_em.exe
          if-no-files-found: error
          retention-days: 7

      # Benchmarks

      - name: Benchmark
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        working-directory: tools/benchmarks
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb
          sudo dpkg -i hyperfine_1.12.0_amd64.deb
          pip install matplotlib numpy six --upgrade
          ./benchmark.sh
          ./mean.py results.json
          ./times.py results.json

      - name: Post Benchmark
        if: matrix.target == 'x86_64-unknown-linux-gnu' && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmark
          path: tools/benchmarks/results.md

      - name: Commit Report
        if: matrix.target == 'x86_64-unknown-linux-gnu' && github.repository == 'three-em/3em' && github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v8
        with:
          add: '["tools/benchmarks/bench_mean.png", "tools/benchmarks/bench_runs.png"]'
          message: "chore:(benchmark): update benchmark results"
          default_author: github_actions
